### ISSUE TITLE
Rendering issue with empty span tags.

### ISSUE THREAD

**Issue by novacrazy** [aickin/react-dom-stream#9] opened 2015-11-02 19:45 UTC
So I have a page-wrapper component that wraps page content in all the boilerplate code of my website to make things easier, and one of the things it processes is error/alert messages from the server to display at the top of the page content.

When there are no messages to display, it just renders as an empty span. However for some reason react-dom-stream@0.2.0-beta.5 is rendering `<span></span>` as `<span< span>`, which mangles parts of the page.

Screenshot of bugged rendering as displayed in the chrome devtools
![bugged](https://cloud.githubusercontent.com/assets/4708645/10892212/ccfef172-8167-11e5-9b60-80ad94774e5c.PNG)

Screenshot of the correct rendering as displayed in the chrome devtools (plus the React hashes since it rerendered it already)
![correct](https://cloud.githubusercontent.com/assets/4708645/10892213/cd042728-8167-11e5-84d4-356c74b5eb06.PNG)

I didn't notice it for a while since the normal React re-renders it correctly on the client immediately.

**Comment by novacrazy** [comment] 2015-11-02 19:49
Also there are a couple `< span>` in there, too. Notice the extra space.

**Comment by aickin** [comment] 2015-11-02 20:12
@novacrazy Thanks for the bug report! 

I probably should have said this somewhere (though I'm not sure where), but the betas I've been putting up should not be used; they have some pretty severe issues. I've been putting them up so that I can get Heroku to pick them up when running test code, but I don't intend for anyone to use them yet.

That all being said, I'd love to add a test case for your bug so that I don't run into it in a real release. Is it something just like this?

```javascript
var Component = ({foo}) => {
  return <span>{foo}</span>;
}

React.renderToString(<Component />, res);
```

**Comment by novacrazy** [comment] 2015-11-02 20:24
Slightly more complicated than that. I have a component named `HiddenElement` that looks like:

```javascript
import * as React from 'react';

export default class HiddenElement extends React.Component {
    static displayName = 'HiddenElement';

    static propTypes = {
        hidden:    React.PropTypes.bool,
        component: React.PropTypes.node
    };

    static defaultProps = {
        component: 'span'
    };

    render() {
        let {hidden, component, children} = this.props;

        let Component = component;

        if( !hidden ) {
            return (
                <Component {...this.props}>{children}</Component>
            );

        } else {
            return <Component/>;
        }
    }
}
```

and a `Message` component that looks like:
```javascript
import * as React from 'react';
import {mixin} from 'mixins';
import PureRenderMixin from '../components/mixins/PureRenderMixin.jsx';
import HiddenElement from '../components/standard/hidden.jsx';

@mixin( PureRenderMixin )
class Message extends React.Component {
    static displayName = 'Message';

    static propTypes = {
        messages:    React.PropTypes.arrayOf( React.PropTypes.string ),
        hideIfEmpty: React.PropTypes.bool,
        style:       React.PropTypes.oneOf( ['primary', 'success', 'info', 'warning', 'danger'] )
    };

    static defaultProps = {
        messages:    [],
        hideIfEmpty: true,
        style:       'primary'
    };

    render() {
        const {children, style, messages, hideIfEmpty} = this.props;

        let panelClassName = 'panel panel-' + style;
        let listGroupItemClassName = 'list-group-item list-group-item-' + (style !== 'primary' ? style : 'info');

        return (
            <HiddenElement hidden={hideIfEmpty && messages.length === 0}>
                <div className={panelClassName}>
                    <div className="panel-heading">
                        <h3 className="panel-title">{children}</h3>
                    </div>
                    <ul className="list-group">
                        {messages.map( ( error, index ) => {
                            return (
                            <li className={listGroupItemClassName} key={index}>{error}</li>
                                );
                            } )}
                    </ul>
                </div>
            </HiddenElement>
        );
    }
}

export default Message;
```

So there might be a couple places that the renderer could mess up, but it does still boil down to `React.createElement("span", ...)` I think. I posted the whole code in case you can identify where it messes up.

Also if it helps, the `PureRenderMixin` mixin just adds the member function `shouldComponentUpdate` that returns `false`. The `'mixins'` module is custom but does exactly what it sounds like, though.

And I know that it shouldn't be used in production, but I went ahead and added support for it on my website since it cuts ~60% off the TTFB response time. Which is actually really impressive.

Hope some of that code helps.

**Comment by aickin** [comment] 2015-11-02 20:58
Cool, thanks for the update, and it does help. I'll leave this open against the 2.x line so I can add a test, and I'll close it out when I think it's addressed.

(FWIW, I'm currently working on the 2.x line, trying to address issue #2 and have the API return a stream. The problem is that it's been a massive performance killer for TTLB. After multiple rewrites and a lot of optimization, I've got it down to ~+15% on TTLB with no network overhead, and I'm thinking of releasing that way this week.)

**Comment by novacrazy** [comment] 2015-11-02 21:09
Don't think I can be of much help to you there. However, also FWIW, I got a chance to play around with the [AsyncWriter](https://github.com/marko-js/async-writer) module lately when integrating Marko into my stack. After looking at some of your code in ReactServerAsyncRendering.js, the AsyncWriter module might come in handy to you, especially since you can layer asynchronous writes and it'll still come out in the correct order.

**Comment by aickin** [comment] 2015-11-13 01:58
Hey @novacrazy, I just released v0.2.0 (which is a total rewrite since the beta you were using, I believe), and I included an empty span test case. Please let me know if this crops up again, but for now, I'm closing the issue. Thanks so much for reporting it!

**Closed by aickin** 2015-11-13 01:58 UTC

**Comment by novacrazy** [comment] 2015-11-13 22:15
Very nice! I can't tell the difference in the generated code now. Though was everything upgraded to 0.14.2?

**Comment by aickin** [comment] 2015-11-13 22:18
Yep, I forked off of the `react` 0.14.2 commit for `react-dom-stream` 0.2.0. Please let me know if you see any more problems!
