### ISSUE TITLE
Fails on function that returns an array

### ISSUE THREAD

**Issue by darobin** [aickin/react-dom-stream#3] opened 2015-10-21 14:46 UTC
I have a product which would greatly benefit from this, so I have it a shot. Unfortunately it doesn't work.

My root component gets rendered fine, as well as its direct children that are components. But then it has further children generated by a function that returns an array of components — those get dropped on the floor. The root component render returns something like:

```
<article>
  <h1>{title}</h1>
  {functionThatReturnsAnArrayOfComponents()}
</article>
```
I get the article with its title but that's it. I don't have time to debug further right now; if I get a change I will investigate later.

**Comment by darobin** [comment] 2015-10-21 14:47
Note: it might just be failing due to the array nature of the return, not the function.

**Comment by aickin** [comment] 2015-10-21 15:06
Thanks for the report @darobin, and sorry it's not working. 

My basic test case uses arrays of children, so it can't be a problem with all arrays. Without being at a computer, though, it's hard to tell what's going on. I'm walking to a doctors appointment right now; I'll investigate when I'm done. 

Thanks again for trying it out, and sorry it's not working right off the bat.

**Comment by aickin** [comment] 2015-10-21 16:06
I was able to make a small example that uses a function that returns an array of elements, and it worked fine for me, so we need to dig further. A few questions if you don't mind:

How do you transform JSX? With what library and version?
Which version of node are you using?
Did it render correctly with React 0.14?
Is anything logged to the console?
What do you see when you view source?

I know that's a lot, but it'll help me track it down. Thanks!

**Comment by aickin** [comment] 2015-10-21 17:50
Another way to track this down would be to install and run https://github.com/aickin/react-dom-stream-example and try out http://localhost:5000/issue3 , which is the small test case I built based on your feedback. It should read out a title with a list of divs ("Foo", "Bar", "Baz).

If that test case doesn't work on your machine, there's probably an environment difference. If it does work, then there's something in your code that's different from the test case.

Thanks for your help!

**Comment by aickin** [comment] 2015-10-24 18:09
Hey there @darobin, do you have any updates on this issue? I'm still not able to reproduce it. Any help you provide would be great!

**Comment by aickin** [comment] 2015-11-13 01:59
Hey @darobin, I have several test cases for this now in place, and I haven't been able to repro it, so I'm going to go ahead and close this issue. Thanks so much for reporting it!

**Closed by aickin** 2015-11-13 01:59 UTC
